CREATE TABLE URUNLER(
URUNID INT PRIMARY KEY IDENTITY,
ADI NVARCHAR(25)
)
GO

CREATE TABLE KATEGORILER(
KATEGORIID INT PRIMARY KEY IDENTITY,
ADI NVARCHAR(25),
URUNFK INT
CONSTRAINT FK_URUNLER_KATEGORILER FOREIGN KEY (URUNFK) REFERENCES URUNLER(URUNID) 
)
GO

CREATE TABLE TEDARIKCI(
TEDARIKCIID INT PRIMARY KEY IDENTITY,
ADI NVARCHAR(25),
URUNFK INT
CONSTRAINT FK_URUNLER_TEDARIKCI FOREIGN KEY (URUNFK) REFERENCES URUNLER(URUNID) 
)
GO

CREATE TABLE MUSTERILER(
MUSTERIID INT PRIMARY KEY IDENTITY,
ADI NVARCHAR(25),
)
GO

CREATE TABLE SIPARISLER(
SIPARISID INT PRIMARY KEY IDENTITY,
URUNFK INT,
MUSTERIFK INT,
ISACTIVE BIT DEFAULT 0
CONSTRAINT FK_URUNLER_SIPARISLER FOREIGN KEY (URUNFK) REFERENCES URUNLER(URUNID) ,
CONSTRAINT FK_SIPARISLER_MUSTERILER FOREIGN KEY (MUSTERIFK) REFERENCES MUSTERILER(MUSTERIID)
)
GO

CREATE VIEW AKTIFSIPARIS as
select m.ADI,s.ISACTIVE from SIPARISLER as s 
inner join MUSTERILER as m on m.MUSTERIID=s.MUSTERIFK
where s.ISACTIVE = 1
group by m.ADI,s.ISACTIVE
go

select * from AKTIFSIPARIS